### ISSUE TITLE
Router.use() requires a middleware function but got a Object

### ISSUE THREAD

**Issue by wasmake** [samuelnovaes/routerfy#1]
Sorry for bothering, I was trying to use your module but I have errors:

`C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\node_modules\express\lib\router\index.js:458
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^

TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\node_modules\express\lib\router\index.js:458:13)
    at walk (C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\node_modules\routerfy\index.js:27:11)
    at middleware (C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\node_modules\routerfy\index.js:39:2)
    at walk (C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\node_modules\routerfy\index.js:30:26)
    at middleware (C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\node_modules\routerfy\index.js:39:2)
    at Object.<anonymous> (C:\Users\Der\Desktop\Akardoo Final\website\akardoo\server\server.js:27:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`

server.js
`// Importing required modules
const cors = require('cors');
const express = require('express');
const routerfy = require('routerfy');

const mongoose = require('mongoose');

const database = require('../config/database.json');

// parse env variables
require('dotenv').config();

// Configuring port
const port = process.env.PORT || 9000;

const app = express();

// database connection
mongoose.connect(database.mongoURI, { useNewUrlParser: true, useUnifiedTopology: true})
  .then(db => console.log('MongoDB Connected...'))
  .catch(err => console.log(err));

// Configure middlewares
app.use(cors());

// Defining route middleware
app.use(routerfy('routes'));

// Listening to port
app.listen(port);
console.log(`Listening On http://localhost:${port}/api`);

module.exports = app;
`

![image](https://user-images.githubusercontent.com/8813159/90822583-4f65e280-e2fa-11ea-9d62-35df125a6cd0.png)

NPM Version: 6.14.5
NodeJS version: v12.18.2

**Comment by wasmake** [comment]
Never mind, route files where empty and that was the issue, marked as solved thanks 👍
